version: '3'

services:
  perfstat:
    container_name: perfstat
    image: flaviostutz/perfstat
    privileged: true
    volumes:
      - /etc/hostname:/etc/hostname
    ports:
      - 8880:8880
    deploy:
      mode: global
    networks:
      -  app

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      -  app


  flash:
    container_name: flash
    build: .
    ports:
      - 8080:8080
    networks:
      -  app

networks:
  app:
    driver: bridge